use std::fs;
use std::path::Path;

fn main() {
    // Ensure the generated directory exists
    let generated_dir = "src/db/generated";
    if !Path::new(generated_dir).exists() {
        fs::create_dir_all(generated_dir).expect("Failed to create generated directory");
    }
    
    // Create a simple empty module
    let mod_content = "// This file is generated by build.rs\n// It used to contain cornucopia generated code\n";
    fs::write(format!("{}/mod.rs", generated_dir), mod_content)
        .expect("Failed to write generated module");
}