# fly.toml app configuration file generated for explorer-api on 2025-06-21T18:28:27+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'explorer-api'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile.api'

[env]
  DATABASE_SCHEMA = 'public'
  PONDER_LOG_LEVEL = 'info'

[http_service]
  internal_port = 42069
  force_https = true
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 2000
    soft_limit = 1000

  [[http_service.checks]]
    interval = '15s'
    timeout = '10s'
    grace_period = '60s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
